# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- script: cd LargeWebStore.Api && dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration) Logs'

#- task: DotNetCoreCLI@2
#  displayName: 'dotnet build LargeWebStore.DWH/LargeWebStore.DWH.csproj'
#  inputs:
#    command: 'dotnet build'
#    projects: 'LargeWebStore.DWH/LargeWebStore.DWH.csproj'
#    arguments: '--configuration $(buildConfiguration)'
