# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'dotnet build LargeWebStore.DWH/LargeWebStore.DWH.csproj'
  inputs:
    command: 'dotnet build'
    projects: 'LargeWebStore.DWH/LargeWebStore.DWH.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build LargeWebStore.DWH.Api/LargeWebStore.DWH.Api.csproj'
  inputs:
    command: 'dotnet build'
    publishWebPprojects: false
    projects: 'LargeWebStore.DWH.Api/LargeWebStore.DWH.Api.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build LargeWebStore.ElasticSearchManager/LargeWebStore.ElasticSearchManager.csproj'
  inputs:
    command: 'dotnet build'
    projects: 'LargeWebStore.ElasticSearchManager/LargeWebStore.ElasticSearchManager.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build LargeWebStore.Logs/LargeWebStore.Logs.csproj'
  inputs:
    command: 'dotnet build'
    projects: 'LargeWebStore.Logs/LargeWebStore.Logs.csproj'
    arguments: '--configuration $(buildConfiguration)'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration) Logs'
